#En este paso relice la instalacion e importacion de libreiras

In [1]:
import numpy as np
import pandas as pd

#se define "df" como variable para realizar la carga de la base de dato

In [4]:
df =  pd.read_csv("base_datos_restaurantes_usa_v2.csv")

#Se realizo la primera inspeccion de la base de datos con el metodo .head de pandas

In [5]:
df.head()

,id_persona,nombre,apellido,edad,genero,ciudad_residencia,estrato_socioeconomico,frecuencia_visita,promedio_gasto_comida,ocio,consume_licor,preferencias_alimenticias,membresia_premium,telefono_contacto,correo_electronico,tipo_de_pago_mas_usado,ingresos_mensuales
0,2550327378,Jackson,Gomez,31.0,Masculino,Miami,Alto,6,67.51,Sí,No,Vegetariano,Sí,(830)220-1926,NaN,Efectivo,6425
1,9446112038,Samantha,Soto,40.0,Femenino,Denver,Medio,2,44.92,Sí,Sí,Mariscos,No,881-476-1426,NaN,Efectivo,2374
2,3098363243,Terry,Adams,62.0,Femenino,Denver,Bajo,2,9.24,Sí,Sí,Vegetariano,No,NaN,diana74@example.net,Efectivo,1110
3,4013002847,James,Shannon,41.0,Masculino,Boston,Alto,5,30.74,Sí,Sí,Carnes,Sí,NaN,scottfrey@example.com,Tarjeta,6931
4,7372911048,Susan,Jones,49.0,Femenino,San Diego,Bajo,0,0.00,No,No,Carnes,No,243.248.8919,glassgary@example.org,Tarjeta,1350

#Se selecciono la ciudad Boston para el analisis correspondiente de los datos especificos de esta ciudad

In [8]:
df_Boston=df[df["ciudad_residencia"] == "Boston"]

#Se utilizo el atributo .shape para saber cuantas filas y columnas correspondia a Boston

In [10]:
df_Boston.shape

(2547, 17)

#aca se hizo identificacion de cantidad de nulos existente por columna

In [11]:
df_Boston.isnull().sum()

id_persona                      0
nombre                          0
apellido                        0
edad                           10
genero                          0
ciudad_residencia               0
estrato_socioeconomico          0
frecuencia_visita               0
promedio_gasto_comida           6
ocio                            0
consume_licor                   0
preferencias_alimenticias     102
membresia_premium               0
telefono_contacto            1264
correo_electronico           1276
tipo_de_pago_mas_usado          0
ingresos_mensuales              0
dtype: int64

#Se utilizo estos dos metodos para sumar los duplicados

In [12]:
df_Boston.duplicated().sum()

np.int64(0)

#Resume los datos de las columnas donde podemos identificar lo vacio o faltnates

In [13]:
df_Boston.info()

<class 'pandas.DataFrame'>
Index: 2547 entries, 3 to 29976
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_persona                 2547 non-null   int64
 1   nombre                     2547 non-null   str
 2   apellido                   2547 non-null   str
 3   edad                       2537 non-null   float64
 4   genero                     2547 non-null   str
 5   ciudad_residencia          2547 non-null   str
 6   estrato_socioeconomico     2547 non-null   str
 7   frecuencia_visita          2547 non-null   int64
 8   promedio_gasto_comida      2541 non-null   float64
 9   ocio                       2547 non-null   str
 10  consume_licor              2547 non-null   str
 11  preferencias_alimenticias  2445 non-null   str
 12  membresia_premium          2547 non-null   str
 13  telefono_contacto          1283 non-null   str
 14  correo_electronico         1271 non-null   str
 15  tipo_de_pago_mas_usado     2547 non-null   str
 16  ingresos_mensuales         2547 non-null   int64
dtypes: float64(2), int64(3), str(12)
memory usage: 358.2 KB

#Con esta funcion se puede detectar aquellas inconsistencias como se aprecia en edad y frecuencia donde los valores son negativos y no corresponden al tipo de dato que deberia estar establecido

In [14]:
df_Boston.describe()

,id_persona,edad,frecuencia_visita,promedio_gasto_comida,ingresos_mensuales
count,2.547000e+03,2537.000000,2547.000000,2541.000000,2547.000000
mean,5.548750e+09,49.512810,3.980762,29.494766,5658.080487
std,2.620686e+09,23.670266,2.792514,23.960740,4725.407151
min,1.010508e+09,-5.000000,-3.000000,0.000000,807.000000
25%,3.234152e+09,33.000000,2.000000,11.340000,1852.500000
50%,5.642463e+09,49.000000,4.000000,22.790000,3657.000000
75%,7.760216e+09,65.000000,6.000000,41.170000,8237.000000
max,9.993177e+09,300.000000,10.000000,104.600000,17972.000000

#ya identificado los valores inconsistentes, se usa un filtro condicional para identifica con mas precision, los registro cuya edad es menor que cero

In [18]:
df_Boston[df_Boston["edad"] < 0]

,id_persona,nombre,apellido,edad,genero,ciudad_residencia,estrato_socioeconomico,frecuencia_visita,promedio_gasto_comida,ocio,consume_licor,preferencias_alimenticias,membresia_premium,telefono_contacto,correo_electronico,tipo_de_pago_mas_usado,ingresos_mensuales
2482,1737293582,Holly,Gallagher,-5.0,Femenino,Boston,Medio,4,22.82,Sí,No,Carnes,No,NaN,websteramanda@example.org,Efectivo,2836
6777,6826129434,Megan,Russell,-5.0,Femenino,Boston,Medio,3,7.20,No,Sí,Pescado,No,NaN,walkerwilliam@example.net,App,2330
14448,9852786935,Crystal,Jenkins,-5.0,Femenino,Boston,Muy Alto,10,69.67,No,Sí,Carnes,Sí,345.625.4596,NaN,Efectivo,12586
24330,3334126899,Beth,Nicholson,-5.0,Femenino,Boston,Alto,4,19.51,Sí,Sí,Vegetariano,Sí,3149433778,NaN,Efectivo,7730
26734,9433104084,Albert,Johnson,-5.0,Masculino,Boston,Alto,-3,11.55,No,No,Mariscos,Sí,NaN,NaN,Efectivo,4451

#de igual forma se realizo el filtrado de edad con esta condicional de mayor a 100 años

In [30]:
df_Boston[(df_Boston["edad"] > 100)]

,id_persona,nombre,apellido,edad,genero,ciudad_residencia,estrato_socioeconomico,frecuencia_visita,promedio_gasto_comida,ocio,consume_licor,preferencias_alimenticias,membresia_premium,telefono_contacto,correo_electronico,tipo_de_pago_mas_usado,ingresos_mensuales
2101,4640435053,Adam,Young,300.0,Masculino,Boston,Medio,4,14.13,No,Sí,Vegetariano,No,NaN,ryan08@example.com,App,2958
2529,6228635509,Jason,Matthews,300.0,Masculino,Boston,Muy Alto,10,85.96,No,No,Mariscos,Sí,(879)385-9416,kathyjones@example.com,Tarjeta,9729
4492,6448324230,Erik,Martinez,300.0,Masculino,Boston,Bajo,3,13.81,No,Sí,Carnes,No,NaN,NaN,Tarjeta,1364
6313,2539612479,Brian,Farrell,300.0,Masculino,Boston,Medio,3,32.56,No,Sí,Carnes,No,370-361-2950x83474,ymolina@example.com,Tarjeta,2892
9661,6934932642,Jonathan,Sims,300.0,Masculino,Boston,Alto,5,5.40,Sí,No,Otro,No,(611)682-4018x8904,jessica55@example.org,Tarjeta,8060
13785,9263135031,Amy,Matthews,300.0,Femenino,Boston,Alto,4,7.58,No,No,Carnes,No,NaN,NaN,App,4382
19943,1546416390,Caleb,Anderson,300.0,Masculino,Boston,Bajo,3,14.57,Sí,Sí,Carnes,No,NaN,NaN,App,1474
24022,3656689261,Anna,Blanchard,300.0,Femenino,Boston,Muy Alto,7,102.93,Sí,Sí,Otro,Sí,NaN,igarza@example.com,Efectivo,10230
28038,2092282503,Bryan,Pratt,300.0,Masculino,Boston,Muy Alto,8,22.44,No,No,Otro,Sí,701-452-1033,lindsay47@example.net,Efectivo,9582

#En este metodo se pudo identificar aquellos datos inconsistentes que tenian numeros negativos

In [19]:
df_Boston[df_Boston["frecuencia_visita"] < 0]

,id_persona,nombre,apellido,edad,genero,ciudad_residencia,estrato_socioeconomico,frecuencia_visita,promedio_gasto_comida,ocio,consume_licor,preferencias_alimenticias,membresia_premium,telefono_contacto,correo_electronico,tipo_de_pago_mas_usado,ingresos_mensuales
496,1420654268,Keith,Hensley,42.0,Masculino,Boston,Muy Alto,-3,104.17,Sí,Sí,Vegano,Sí,NaN,raymondbeasley@example.org,Efectivo,9806
602,9674596936,Lauren,Kelly,19.0,Femenino,Boston,Medio,-3,5.88,Sí,Sí,NaN,No,445.962.1555,eric16@example.net,App,2726
734,9190753627,Danielle,Abbott,27.0,Femenino,Boston,Medio,-3,13.69,No,Sí,Pescado,No,365-598-1157,cbass@example.net,Efectivo,2450
969,9872029928,Sarah,Miller,42.0,Femenino,Boston,Alto,-3,36.58,No,Sí,Vegetariano,No,NaN,kellystone@example.com,App,6940
1051,5853660504,Victor,Gibbs,68.0,Masculino,Boston,Bajo,-3,13.22,Sí,No,Pescado,No,001-586-421-7008x781,davisdaniel@example.org,Efectivo,1265
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29124,3937505620,Sarah,Collins,71.0,Femenino,Boston,Muy Alto,-3,89.25,Sí,No,Carnes,Sí,NaN,NaN,Tarjeta,10280
29247,4540608132,Michelle,Thompson,70.0,Femenino,Boston,Alto,-3,7.45,No,No,Vegetariano,Sí,+1-449-217-8781x98931,matthewthomas@example.org,Tarjeta,5923
29354,8914054579,Ellen,Foster,41.0,Femenino,Boston,Medio,-3,30.28,Sí,No,Carnes,Sí,NaN,NaN,Efectivo,2071
29750,6869865000,Sandra,Cisneros,37.0,Femenino,Boston,Alto,-3,20.93,Sí,No,Carnes,No,NaN,NaN,Tarjeta,6999
29944,5463363175,Aaron,Charles,37.0,Masculino,Boston,Alto,-3,11.29,Sí,No,Mariscos,Sí,304.516.7648,alan64@example.net,Efectivo,8224

#Promediando con esta funcion se puede verificar nuevamente los datos inconsistentes relacionados a esta columna

In [20]:
df_Boston["promedio_gasto_comida"].describe()

count    2541.000000
mean       29.494766
std        23.960740
min         0.000000
25%        11.340000
50%        22.790000
75%        41.170000
max       104.600000
Name: promedio_gasto_comida, dtype: float64

#Se verifica si hay un dato por debajo de 0

In [28]:
(df_Boston["promedio_gasto_comida"] < 0).sum()

np.int64(0)

#Con este metodo se puede ordenar los datos de mayo a menor, incluyendo los vacion de cada columna y identificar las preferencias del cliente

In [32]:
(df_Boston["preferencias_alimenticias"].value_counts(dropna=False))

preferencias_alimenticias
Vegetariano    708
Carnes         535
Mariscos       493
Pescado        272
Vegano         239
Otro           198
NaN            102
Name: count, dtype: int64

# en este punto se identifica la tendencia de consumo de licor

In [33]:
(df_Boston["consume_licor"].value_counts(dropna=False))

consume_licor
Sí    1612
No     935
Name: count, dtype: int64

# col el mismo metodo identificamos la tendencia de genero

In [34]:
(df_Boston["genero"].value_counts(dropna=False))

genero
Femenino     1309
Masculino    1238
Name: count, dtype: int64

#y por ultimo con el metodo se ordena de mayor a menos el estatro socioeconomico de los clientes

In [35]:
(df_Boston["estrato_socioeconomico"].value_counts(dropna=False))

estrato_socioeconomico
Alto        759
Medio       729
Muy Alto    533
Bajo        526
Name: count, dtype: int64